/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaListarOrdendesDeFabricacion.java
 *
 * Created on 03/12/2011, 03:48:28
 */
package interfacesGraficas;

import interfacesGraficas.Controladores.ControladorListarOrdenesDeFabricacion;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JToolBar;

/**
 *
 * @author rustu
 */
public class PantallaListarOrdendesDeFabricacion extends javax.swing.JDialog {

    ControladorListarOrdenesDeFabricacion controlador;

    /** Creates new form PantallaListarOrdendesDeFabricacion */
    public PantallaListarOrdendesDeFabricacion(java.awt.Frame parent, boolean modal, ControladorListarOrdenesDeFabricacion control) {
        super(parent, modal);
        initComponents();
        controlador = control;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        guardar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrdenesDeProduccion = new javax.swing.JTable();
        estadoOrdenLabel = new javax.swing.JLabel();
        estadoOrdenListBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades/imagenes/iconos/Save_30.png"))); // NOI18N
        guardar.setToolTipText("Guardar");
        guardar.setFocusable(false);
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(guardar);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades/imagenes/iconos/Log-out-30.png"))); // NOI18N
        salir.setToolTipText("Salir");
        salir.setFocusable(false);
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jToolBar1.add(salir);

        tablaOrdenesDeProduccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaOrdenesDeProduccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaOrdenesDeProduccionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaOrdenesDeProduccion);

        estadoOrdenLabel.setText("Estado de la orden");

        estadoOrdenListBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Generada", "En curso", "Finalizada" }));
        estadoOrdenListBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoOrdenListBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(estadoOrdenLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadoOrdenListBox, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(233, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoOrdenLabel)
                    .addComponent(estadoOrdenListBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void estadoOrdenListBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoOrdenListBoxActionPerformed
    controlador.listarOrdenes();
}//GEN-LAST:event_estadoOrdenListBoxActionPerformed

private void tablaOrdenesDeProduccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaOrdenesDeProduccionMouseClicked
    if (evt.getClickCount() == 2) {
        controlador.editarOrden();
    }
}//GEN-LAST:event_tablaOrdenesDeProduccionMouseClicked

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dispose();

    }//GEN-LAST:event_salirActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel estadoOrdenLabel;
    private javax.swing.JComboBox estadoOrdenListBox;
    private javax.swing.JButton guardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton salir;
    private javax.swing.JTable tablaOrdenesDeProduccion;
    // End of variables declaration//GEN-END:variables

    public JLabel getEstadoOrdenLabel() {
        return estadoOrdenLabel;
    }

    public void setEstadoOrdenLabel(JLabel estadoOrdenLabel) {
        this.estadoOrdenLabel = estadoOrdenLabel;
    }

    public JComboBox getEstadoOrdenListBox() {
        return estadoOrdenListBox;
    }

    public void setEstadoOrdenListBox(JComboBox estadoOrdenListBox) {
        this.estadoOrdenListBox = estadoOrdenListBox;
    }

    public JButton getGuardar() {
        return guardar;
    }

    public void setGuardar(JButton guardar) {
        this.guardar = guardar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JButton getSalir() {
        return salir;
    }

    public void setSalir(JButton salir) {
        this.salir = salir;
    }

    public JTable getTablaOrdenesDeProduccion() {
        return tablaOrdenesDeProduccion;
    }

    public void setTablaOrdenesDeProduccion(JTable tablaOrdenesDeProduccion) {
        this.tablaOrdenesDeProduccion = tablaOrdenesDeProduccion;
    }

    public ControladorListarOrdenesDeFabricacion getControlador() {
        return controlador;
    }

    public void setControlador(ControladorListarOrdenesDeFabricacion controlador) {
        this.controlador = controlador;
    }
}
