/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJDialog.java
 *
 * Created on 19/10/2011, 20:00:38
 */
package interfacesGraficas;

import interfacesGraficas.Controladores.ControladorMateriaPrima;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToolBar;

/**
 *
 * @author rustu
 */
public class PantallaCrearMateriaPrima extends javax.swing.JDialog {
    
    ControladorMateriaPrima controlador;
    
    /** Creates new form NewJDialog */
    public PantallaCrearMateriaPrima(java.awt.Frame parent, boolean modal, ControladorMateriaPrima controladorMP) {
        super(parent, modal);
        initComponents();
        controlador = controladorMP;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        toolbar = new javax.swing.JToolBar();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        codigoTextBox = new javax.swing.JTextField();
        nombreTextBox = new javax.swing.JTextField();
        ubicacionEnElAlmacenLabel = new javax.swing.JLabel();
        unidadDeMedidaLabel = new javax.swing.JLabel();
        tamañoLoteEstandarLabel = new javax.swing.JLabel();
        observacionLabel = new javax.swing.JLabel();
        precioBaseLabel = new javax.swing.JLabel();
        categoriaLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        descripcionLabel = new javax.swing.JLabel();
        costoUnitarioPorOmisionLabel = new javax.swing.JLabel();
        costoEstandarLabel = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        fechaDeVencimientoLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        categoriaListBox = new javax.swing.JComboBox();
        costoEstandarTextBox = new javax.swing.JTextField();
        costoUnitarioPorOmisionTextBox = new javax.swing.JTextField();
        fechaVencimientoTextBox = new javax.swing.JTextField();
        precioBaseTextBox = new javax.swing.JTextField();
        tamanioLoteEstandarTextBox = new javax.swing.JTextField();
        estadoListBox = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        observacionTextArea = new javax.swing.JTextArea();
        ubicacionAlamcenTextBox = new javax.swing.JTextField();
        unidadDeMedidaListBox = new javax.swing.JComboBox();
        estadoFechaEntrarActividadTextBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        toolbar.setRollover(true);

        guardar.setText("Guardar");
        guardar.setFocusable(false);
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        toolbar.add(guardar);

        cancelar.setText("Cancelar");
        cancelar.setFocusable(false);
        cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(cancelar);

        salir.setText("Salir");
        salir.setFocusable(false);
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(salir);

        descripcionTextArea.setColumns(20);
        descripcionTextArea.setRows(5);
        jScrollPane1.setViewportView(descripcionTextArea);

        ubicacionEnElAlmacenLabel.setText("Ubicación en el almacén");

        unidadDeMedidaLabel.setText("Unidad de medida");

        tamañoLoteEstandarLabel.setText("Tamaño lote estandar");

        observacionLabel.setText("Observación");

        precioBaseLabel.setText("Precio base");

        categoriaLabel.setText("Categoria");

        nombreLabel.setText("Nombre");

        descripcionLabel.setText("Descripcion");

        costoUnitarioPorOmisionLabel.setText("Costo unitario por omisión");

        costoEstandarLabel.setText("Costo Estandar");

        codigoLabel.setText("Código");

        fechaDeVencimientoLabel.setText("Fecha de vencimiento");

        estadoLabel.setText("Estado");

        categoriaListBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));

        estadoListBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        estadoListBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoListBoxActionPerformed(evt);
            }
        });

        observacionTextArea.setColumns(20);
        observacionTextArea.setRows(5);
        jScrollPane3.setViewportView(observacionTextArea);

        unidadDeMedidaListBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Litros", "Kilios", "Gramos", "Cm3" }));

        jLabel1.setText("Entrar en actividad en");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoLabel)
                            .addComponent(nombreLabel)
                            .addComponent(descripcionLabel)
                            .addComponent(unidadDeMedidaLabel))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unidadDeMedidaListBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)))
                    .addComponent(estadoLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoriaLabel)
                            .addComponent(costoEstandarLabel)
                            .addComponent(costoUnitarioPorOmisionLabel)
                            .addComponent(precioBaseLabel)
                            .addComponent(fechaDeVencimientoLabel)
                            .addComponent(tamañoLoteEstandarLabel))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(estadoListBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoFechaEntrarActividadTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(categoriaListBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3)
                            .addComponent(costoUnitarioPorOmisionTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaVencimientoTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tamanioLoteEstandarTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ubicacionAlamcenTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoEstandarTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(precioBaseTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(ubicacionEnElAlmacenLabel)
                    .addComponent(observacionLabel))
                .addGap(322, 322, 322))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel)
                    .addComponent(codigoTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcionLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadDeMedidaListBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidadDeMedidaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaLabel)
                    .addComponent(categoriaListBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costoEstandarLabel)
                    .addComponent(costoEstandarTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costoUnitarioPorOmisionLabel)
                    .addComponent(costoUnitarioPorOmisionTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioBaseLabel)
                    .addComponent(precioBaseTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoLabel)
                    .addComponent(estadoListBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(estadoFechaEntrarActividadTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaDeVencimientoLabel)
                    .addComponent(fechaVencimientoTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamañoLoteEstandarLabel)
                    .addComponent(tamanioLoteEstandarTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubicacionEnElAlmacenLabel)
                    .addComponent(ubicacionAlamcenTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(observacionLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toolbar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void estadoListBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoListBoxActionPerformed
    if(((String)estadoListBox.getModel().getSelectedItem()).equals("Inactivo")){
        estadoFechaEntrarActividadTextBox.setEditable(true);
    }else{
        estadoFechaEntrarActividadTextBox.setEditable(false);
    }
}//GEN-LAST:event_estadoListBoxActionPerformed

private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
    controlador.guardar();
}//GEN-LAST:event_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel categoriaLabel;
    private javax.swing.JComboBox categoriaListBox;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTextBox;
    private javax.swing.JLabel costoEstandarLabel;
    private javax.swing.JTextField costoEstandarTextBox;
    private javax.swing.JLabel costoUnitarioPorOmisionLabel;
    private javax.swing.JTextField costoUnitarioPorOmisionTextBox;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JTextArea descripcionTextArea;
    private javax.swing.JTextField estadoFechaEntrarActividadTextBox;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JComboBox estadoListBox;
    private javax.swing.JLabel fechaDeVencimientoLabel;
    private javax.swing.JTextField fechaVencimientoTextBox;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextBox;
    private javax.swing.JLabel observacionLabel;
    private javax.swing.JTextArea observacionTextArea;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel precioBaseLabel;
    private javax.swing.JTextField precioBaseTextBox;
    private javax.swing.JButton salir;
    private javax.swing.JTextField tamanioLoteEstandarTextBox;
    private javax.swing.JLabel tamañoLoteEstandarLabel;
    private javax.swing.JToolBar toolbar;
    private javax.swing.JTextField ubicacionAlamcenTextBox;
    private javax.swing.JLabel ubicacionEnElAlmacenLabel;
    private javax.swing.JLabel unidadDeMedidaLabel;
    private javax.swing.JComboBox unidadDeMedidaListBox;
    // End of variables declaration//GEN-END:variables

    public JButton getCancelar() {
        return cancelar;
    }

    public void setCancelar(JButton cancelar) {
        this.cancelar = cancelar;
    }

    public JLabel getCategoriaLabel() {
        return categoriaLabel;
    }

    public void setCategoriaLabel(JLabel categoriaLabel) {
        this.categoriaLabel = categoriaLabel;
    }

    public JComboBox getCategoriaListBox() {
        return categoriaListBox;
    }

    public void setCategoriaListBox(JComboBox categoriaListBox) {
        this.categoriaListBox = categoriaListBox;
    }

    public JLabel getCodigoLabel() {
        return codigoLabel;
    }

    public void setCodigoLabel(JLabel codigoLabel) {
        this.codigoLabel = codigoLabel;
    }

    public JTextField getCodigoTextBox() {
        return codigoTextBox;
    }

    public void setCodigoTextBox(JTextField codigoTextBox) {
        this.codigoTextBox = codigoTextBox;
    }

    public ControladorMateriaPrima getControlador() {
        return controlador;
    }

    public void setControlador(ControladorMateriaPrima controlador) {
        this.controlador = controlador;
    }

    public JLabel getCostoEstandarLabel() {
        return costoEstandarLabel;
    }

    public void setCostoEstandarLabel(JLabel costoEstandarLabel) {
        this.costoEstandarLabel = costoEstandarLabel;
    }

    public JTextField getCostoEstandarTextBox() {
        return costoEstandarTextBox;
    }

    public void setCostoEstandarTextBox(JTextField costoEstandarTextBox) {
        this.costoEstandarTextBox = costoEstandarTextBox;
    }

    public JLabel getCostoUnitarioPorOmisionLabel() {
        return costoUnitarioPorOmisionLabel;
    }

    public void setCostoUnitarioPorOmisionLabel(JLabel costoUnitarioPorOmisionLabel) {
        this.costoUnitarioPorOmisionLabel = costoUnitarioPorOmisionLabel;
    }

    public JTextField getCostoUnitarioPorOmisionTextBox() {
        return costoUnitarioPorOmisionTextBox;
    }

    public void setCostoUnitarioPorOmisionTextBox(JTextField costoUnitarioPorOmisionTextBox) {
        this.costoUnitarioPorOmisionTextBox = costoUnitarioPorOmisionTextBox;
    }

    public JLabel getDescripcionLabel() {
        return descripcionLabel;
    }

    public void setDescripcionLabel(JLabel descripcionLabel) {
        this.descripcionLabel = descripcionLabel;
    }

    public JTextArea getDescripcionTextArea() {
        return descripcionTextArea;
    }

    public void setDescripcionTextArea(JTextArea descripcionTextArea) {
        this.descripcionTextArea = descripcionTextArea;
    }

    public JTextField getEstadoFechaEntrarActividadTextBox() {
        return estadoFechaEntrarActividadTextBox;
    }

    public void setEstadoFechaEntrarActividadTextBox(JTextField estadoFechaEntrarActividadTextBox) {
        this.estadoFechaEntrarActividadTextBox = estadoFechaEntrarActividadTextBox;
    }

    public JLabel getEstadoLabel() {
        return estadoLabel;
    }

    public void setEstadoLabel(JLabel estadoLabel) {
        this.estadoLabel = estadoLabel;
    }

    public JComboBox getEstadoListBox() {
        return estadoListBox;
    }

    public void setEstadoListBox(JComboBox estadoListBox) {
        this.estadoListBox = estadoListBox;
    }

    public JLabel getFechaDeVencimientoLabel() {
        return fechaDeVencimientoLabel;
    }

    public void setFechaDeVencimientoLabel(JLabel fechaDeVencimientoLabel) {
        this.fechaDeVencimientoLabel = fechaDeVencimientoLabel;
    }

    public JTextField getFechaVencimientoTextBox() {
        return fechaVencimientoTextBox;
    }

    public void setFechaVencimientoTextBox(JTextField fechaVencimientoTextBox) {
        this.fechaVencimientoTextBox = fechaVencimientoTextBox;
    }

    public JButton getGuardar() {
        return guardar;
    }

    public void setGuardar(JButton guardar) {
        this.guardar = guardar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JLabel getNombreLabel() {
        return nombreLabel;
    }

    public void setNombreLabel(JLabel nombreLabel) {
        this.nombreLabel = nombreLabel;
    }

    public JTextField getNombreTextBox() {
        return nombreTextBox;
    }

    public void setNombreTextBox(JTextField nombreTextBox) {
        this.nombreTextBox = nombreTextBox;
    }

    public JLabel getObservacionLabel() {
        return observacionLabel;
    }

    public void setObservacionLabel(JLabel observacionLabel) {
        this.observacionLabel = observacionLabel;
    }

    public JTextArea getObservacionTextArea() {
        return observacionTextArea;
    }

    public void setObservacionTextArea(JTextArea observacionTextArea) {
        this.observacionTextArea = observacionTextArea;
    }

    public JPanel getPanelPrincipal() {
        return panelPrincipal;
    }

    public void setPanelPrincipal(JPanel panelPrincipal) {
        this.panelPrincipal = panelPrincipal;
    }

    public JLabel getPrecioBaseLabel() {
        return precioBaseLabel;
    }

    public void setPrecioBaseLabel(JLabel precioBaseLabel) {
        this.precioBaseLabel = precioBaseLabel;
    }

    public JTextField getPrecioBaseTextBox() {
        return precioBaseTextBox;
    }

    public void setPrecioBaseTextBox(JTextField precioBaseTextBox) {
        this.precioBaseTextBox = precioBaseTextBox;
    }

    public JButton getSalir() {
        return salir;
    }

    public void setSalir(JButton salir) {
        this.salir = salir;
    }

    public JTextField getTamanioLoteEstandarTextBox() {
        return tamanioLoteEstandarTextBox;
    }

    public void setTamanioLoteEstandarTextBox(JTextField tamanioLoteEstandarTextBox) {
        this.tamanioLoteEstandarTextBox = tamanioLoteEstandarTextBox;
    }

    public JLabel getTamañoLoteEstandarLabel() {
        return tamañoLoteEstandarLabel;
    }

    public void setTamañoLoteEstandarLabel(JLabel tamañoLoteEstandarLabel) {
        this.tamañoLoteEstandarLabel = tamañoLoteEstandarLabel;
    }

    public JToolBar getToolbar() {
        return toolbar;
    }

    public void setToolbar(JToolBar toolbar) {
        this.toolbar = toolbar;
    }

    public JTextField getUbicacionAlamcenTextBox() {
        return ubicacionAlamcenTextBox;
    }

    public void setUbicacionAlamcenTextBox(JTextField ubicacionAlamcenTextBox) {
        this.ubicacionAlamcenTextBox = ubicacionAlamcenTextBox;
    }

    public JLabel getUbicacionEnElAlmacenLabel() {
        return ubicacionEnElAlmacenLabel;
    }

    public void setUbicacionEnElAlmacenLabel(JLabel ubicacionEnElAlmacenLabel) {
        this.ubicacionEnElAlmacenLabel = ubicacionEnElAlmacenLabel;
    }

    public JLabel getUnidadDeMedidaLabel() {
        return unidadDeMedidaLabel;
    }

    public void setUnidadDeMedidaLabel(JLabel unidadDeMedidaLabel) {
        this.unidadDeMedidaLabel = unidadDeMedidaLabel;
    }

    public JComboBox getUnidadDeMedidaListBox() {
        return unidadDeMedidaListBox;
    }

    public void setUnidadDeMedidaListBox(JComboBox unidadDeMedidaListBox) {
        this.unidadDeMedidaListBox = unidadDeMedidaListBox;
    }



}
