/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJDialog.java
 *
 * Created on 19/10/2011, 20:00:38
 */
package interfacesGraficas;

/**
 *
 * @author rustu
 */
public class PantallaCrearMateriaPrima extends javax.swing.JDialog {

    /** Creates new form NewJDialog */
    public PantallaCrearMateriaPrima(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        categoriaLabel = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        costoEstandarLabel = new javax.swing.JLabel();
        costoUnitarioPorOmisionLabel = new javax.swing.JLabel();
        descripcionLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        fechaDeVencimientoLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        observacionLabel = new javax.swing.JLabel();
        precioBaseLabel = new javax.swing.JLabel();
        tamañoLoteEstandarLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        ubicacionEnElAlmacenLabel = new javax.swing.JLabel();
        unidadDeMedidaLabel = new javax.swing.JLabel();
        proveedorPredeterminadoLabel = new javax.swing.JLabel();
        proveedorPredeterminadoComboBox = new javax.swing.JComboBox();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        categoriaLabel.setText("Categoria");

        codigoLabel.setText("Código");

        costoEstandarLabel.setText("Costo Estandar");

        costoUnitarioPorOmisionLabel.setText("Costo unitario por omision");

        descripcionLabel.setText("Descripcion");

        estadoLabel.setText("Estado");

        fechaDeVencimientoLabel.setText("Fecha de vencimiento");

        nombreLabel.setText("Nombre");

        observacionLabel.setText("Observación");

        precioBaseLabel.setText("Precio base");

        tamañoLoteEstandarLabel.setText("Tamaño lote estandar");

        tipoLabel.setText("Tipo");

        ubicacionEnElAlmacenLabel.setText("Ubicación en el almacén");

        unidadDeMedidaLabel.setText("Unidad de medida");

        proveedorPredeterminadoLabel.setText("proveedor predeterminado");

        proveedorPredeterminadoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcionLabel)
                    .addComponent(estadoLabel)
                    .addComponent(fechaDeVencimientoLabel)
                    .addComponent(codigoLabel)
                    .addComponent(observacionLabel)
                    .addComponent(costoUnitarioPorOmisionLabel)
                    .addComponent(nombreLabel)
                    .addComponent(costoEstandarLabel)
                    .addComponent(precioBaseLabel)
                    .addComponent(tamañoLoteEstandarLabel)
                    .addComponent(tipoLabel)
                    .addComponent(ubicacionEnElAlmacenLabel)
                    .addComponent(unidadDeMedidaLabel)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(proveedorPredeterminadoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(proveedorPredeterminadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(categoriaLabel))
                .addContainerGap(428, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codigoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(observacionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoriaLabel)
                .addGap(9, 9, 9)
                .addComponent(costoEstandarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costoUnitarioPorOmisionLabel)
                .addGap(12, 12, 12)
                .addComponent(descripcionLabel)
                .addGap(18, 18, 18)
                .addComponent(estadoLabel)
                .addGap(18, 18, 18)
                .addComponent(fechaDeVencimientoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precioBaseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tamañoLoteEstandarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoLabel)
                .addGap(18, 18, 18)
                .addComponent(ubicacionEnElAlmacenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unidadDeMedidaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedorPredeterminadoLabel)
                    .addComponent(proveedorPredeterminadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        menu.add(jMenu1);

        jMenu2.setText("Edit");
        menu.add(jMenu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PantallaCrearMateriaPrima dialog = new PantallaCrearMateriaPrima(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoriaLabel;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JLabel costoEstandarLabel;
    private javax.swing.JLabel costoUnitarioPorOmisionLabel;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel fechaDeVencimientoLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel observacionLabel;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel precioBaseLabel;
    private javax.swing.JComboBox proveedorPredeterminadoComboBox;
    private javax.swing.JLabel proveedorPredeterminadoLabel;
    private javax.swing.JLabel tamañoLoteEstandarLabel;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JLabel ubicacionEnElAlmacenLabel;
    private javax.swing.JLabel unidadDeMedidaLabel;
    // End of variables declaration//GEN-END:variables
}
