/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaMadre.java
 *
 * Created on 19/10/2011, 19:14:23
 */
package interfacesGraficas;

/**
 *
 * @author rustu
 */
public class PantallaMadre extends javax.swing.JFrame {

    /** Creates new form PantallaMadre */
    public PantallaMadre() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        articulos = new javax.swing.JMenu();
        estructuraDeProducto = new javax.swing.JMenu();
        centrosDeTrabajo = new javax.swing.JMenu();
        crearCentro = new javax.swing.JMenuItem();
        editarCentro = new javax.swing.JMenuItem();
        rutaDeFabricacion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        articulos.setText("Articulos");
        jMenuBar1.add(articulos);

        estructuraDeProducto.setText("Estructura de Prodocto");
        jMenuBar1.add(estructuraDeProducto);

        centrosDeTrabajo.setText("Centros de trabajo");

        crearCentro.setText("Crear centro");
        centrosDeTrabajo.add(crearCentro);

        editarCentro.setText("Editar centro");
        centrosDeTrabajo.add(editarCentro);

        jMenuBar1.add(centrosDeTrabajo);

        rutaDeFabricacion.setText("Ruta de fabricación");
        jMenuBar1.add(rutaDeFabricacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaMadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaMadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaMadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaMadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
      java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PantallaMadre().setVisible(true);
            }
        });
    }
     * 
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu articulos;
    private javax.swing.JMenu centrosDeTrabajo;
    private javax.swing.JMenuItem crearCentro;
    private javax.swing.JMenuItem editarCentro;
    private javax.swing.JMenu estructuraDeProducto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu rutaDeFabricacion;
    // End of variables declaration//GEN-END:variables
}
