/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaABMIndices.java
 *
 * Created on 04/12/2011, 20:35:14
 */
package interfacesGraficas;

import excepciones.ExpertoCostosFijosException;
import interfacesGraficas.Controladores.ControladorABMIndices;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JToolBar;

/**
 *
 * @author edu
 */
public class PantallaABMIndices extends javax.swing.JDialog {
ControladorABMIndices controlador;
    /** Creates new form PantallaABMIndices */
    public PantallaABMIndices(java.awt.Frame parent, boolean modal, ControladorABMIndices contr) {
        super(parent, modal);
        initComponents();
        controlador= contr;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        botonSalur = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonEstructuraFinanciera = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botonRotacion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        botonRentabilidad = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        botonVentas = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        botonCalidad = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        botonClimaSocial = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jToolBar1.setRollover(true);

        botonSalur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades/imagenes/iconos/Log-out-30.png"))); // NOI18N
        botonSalur.setToolTipText("Salir");
        botonSalur.setFocusable(false);
        botonSalur.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalur.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonSalur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalurActionPerformed(evt);
            }
        });
        jToolBar1.add(botonSalur);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jToolBar1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Estructura Financiera"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        botonEstructuraFinanciera.setText("Estructura Financiera");
        botonEstructuraFinanciera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstructuraFinancieraActionPerformed(evt);
            }
        });
        jPanel2.add(botonEstructuraFinanciera, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Rotación"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        botonRotacion.setText("Rotacion");
        botonRotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRotacionActionPerformed(evt);
            }
        });
        jPanel3.add(botonRotacion, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Rentabilidad"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        botonRentabilidad.setText("Rentabilidad");
        botonRentabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRentabilidadActionPerformed(evt);
            }
        });
        jPanel4.add(botonRentabilidad, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel4, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventas"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        botonVentas.setText("Ventas");
        botonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasActionPerformed(evt);
            }
        });
        jPanel5.add(botonVentas, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel5, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Calidad"));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        botonCalidad.setText("Calidad");
        botonCalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalidadActionPerformed(evt);
            }
        });
        jPanel6.add(botonCalidad, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel6, gridBagConstraints);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Rendimiento"));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jButton6.setText("Rendimiento");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel7, gridBagConstraints);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock"));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jButton5.setText("Stock");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel8, gridBagConstraints);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Clima Social"));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        botonClimaSocial.setText("Clima Social");
        botonClimaSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClimaSocialActionPerformed(evt);
            }
        });
        jPanel9.add(botonClimaSocial, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel9, gridBagConstraints);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Relación con los Clientes"));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jButton4.setText("Relacion con CLiente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton4, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel10, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void botonSalurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalurActionPerformed
    dispose();
}//GEN-LAST:event_botonSalurActionPerformed

private void botonEstructuraFinancieraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstructuraFinancieraActionPerformed
    controlador.crearEstructuraFinanciera();
}//GEN-LAST:event_botonEstructuraFinancieraActionPerformed

private void botonRentabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRentabilidadActionPerformed
    controlador.crearRentabilidad();
    
}//GEN-LAST:event_botonRentabilidadActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    controlador.crearStock();
    
}//GEN-LAST:event_jButton5ActionPerformed

private void botonClimaSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClimaSocialActionPerformed
    controlador.crearClimaSocial();
}//GEN-LAST:event_botonClimaSocialActionPerformed

private void botonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentasActionPerformed
    controlador.crearVentas();
            
}//GEN-LAST:event_botonVentasActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    controlador.crearRElacionCliente();
    
}//GEN-LAST:event_jButton4ActionPerformed

private void botonCalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalidadActionPerformed
    controlador.crearCalidad();
    
}//GEN-LAST:event_botonCalidadActionPerformed

private void botonRotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRotacionActionPerformed
    controlador.crearRotacion();
}//GEN-LAST:event_botonRotacionActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    controlador.crearRendimiento();
}//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalidad;
    private javax.swing.JButton botonClimaSocial;
    private javax.swing.JButton botonEstructuraFinanciera;
    private javax.swing.JButton botonRentabilidad;
    private javax.swing.JButton botonRotacion;
    private javax.swing.JButton botonSalur;
    private javax.swing.JButton botonVentas;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

   


    public JButton getBotonSalur() {
        return botonSalur;
    }

    public void setBotonSalur(JButton botonSalur) {
        this.botonSalur = botonSalur;
    }



   
    
}
