/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pantallaPromedioPonderadoMovil.java
 *
 * Created on 04/12/2011, 21:41:33
 */
package interfacesGraficas;

import DTOs.DTOPromedioPonderadoMovil;
import interfacesGraficas.ModeloTablas.ModeloTablaPromedioPonderadoMovil;
import java.util.List;

/**
 *
 * @author rustu
 */
public class pantallaPromedioPonderadoMovil extends javax.swing.JDialog {

    /** Creates new form pantallaPromedioPonderadoMovil */
    public pantallaPromedioPonderadoMovil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        errorPromedioLable = new javax.swing.JLabel();
        errorPromedioTextBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(tabla);

        errorPromedioLable.setText("Error promedio");

        errorPromedioTextBox.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorPromedioLable)
                .addGap(2, 2, 2)
                .addComponent(errorPromedioTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorPromedioLable)
                    .addComponent(errorPromedioTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void iniciar(List<DTOPromedioPonderadoMovil> lista, double errorPromedio){
    
        ModeloTablaPromedioPonderadoMovil mod = new ModeloTablaPromedioPonderadoMovil();
        mod.setListaElementos(lista);
        tabla.setModel(mod);
        errorPromedioTextBox.setText(String.valueOf(errorPromedio));
        setLocationRelativeTo(null);
        setVisible(true);
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorPromedioLable;
    private javax.swing.JTextField errorPromedioTextBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
