/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaABMCostosVariables.java
 *
 * Created on 29/11/2011, 16:59:24
 */
package interfacesGraficas;

import interfacesGraficas.Controladores.ControladorPrediccionDemanda;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToolBar;

/**
 *
 * @author edu
 */
public class PantallaPrediccionDemanda extends javax.swing.JDialog {

    ControladorPrediccionDemanda controlador;

    /** Creates new form PantallaABMCostosVariables */
    public PantallaPrediccionDemanda(java.awt.Frame parent, boolean modal, ControladorPrediccionDemanda contr) {
        super(parent, modal);
        initComponents();
        controlador = contr;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        botonGenerar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        comboBoxPeriodos = new javax.swing.JComboBox();
        jLabelAlfa = new javax.swing.JLabel();
        jLabelPeriodos = new javax.swing.JLabel();
        jComboBoxAlfa = new javax.swing.JComboBox();
        jLabelBeta = new javax.swing.JLabel();
        jComboBoxBeta = new javax.swing.JComboBox();
        jLabelGama = new javax.swing.JLabel();
        jComboBoxGama = new javax.swing.JComboBox();
        jLabelError = new javax.swing.JLabel();
        jComboBoxError = new javax.swing.JComboBox();
        jLabelMetodo = new javax.swing.JLabel();
        jComboBoxMetodo = new javax.swing.JComboBox();
        jLabelProducto = new javax.swing.JLabel();
        jComboBoxProducto = new javax.swing.JComboBox();
        periodoDeInicioLabel = new javax.swing.JLabel();
        jComboBoxperiodoDeInicio = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        botonGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades/imagenes/iconos/agt_action_success-20.png"))); // NOI18N
        botonGenerar.setToolTipText("Calcular");
        botonGenerar.setFocusable(false);
        botonGenerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGenerar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarActionPerformed(evt);
            }
        });
        jToolBar1.add(botonGenerar);

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades/imagenes/iconos/Log-out-30.png"))); // NOI18N
        botonSalir.setToolTipText("Salir");
        botonSalir.setFocusable(false);
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(botonSalir);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametros"));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 320));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 320));

        comboBoxPeriodos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        jLabelAlfa.setText("Alfa:");

        jLabelPeriodos.setText("Periodos a predecir:");

        jComboBoxAlfa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9" }));

        jLabelBeta.setText("Beta:");

        jComboBoxBeta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9" }));

        jLabelGama.setText("Gama:");

        jComboBoxGama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9" }));

        jLabelError.setText("% de error aceptable:");

        jComboBoxError.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "5", "8", "10", "15", "20", "25", "30", "40", "50" }));

        jLabelMetodo.setText("Metodo de predicción de la demanda");

        jComboBoxMetodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Promedio ponderado movil", "Promedio ponderado Exponencialmente", "Metodo Regresion lineal", "Metodo Estacionalidad" }));
        jComboBoxMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMetodoActionPerformed(evt);
            }
        });

        jLabelProducto.setText("Producto");

        jComboBoxProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductoActionPerformed(evt);
            }
        });

        periodoDeInicioLabel.setText("Periodo de inicio");

        jComboBoxperiodoDeInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPeriodos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAlfa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelBeta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelGama, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelError, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMetodo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboBoxPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(periodoDeInicioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxperiodoDeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProducto, 0, 292, Short.MAX_VALUE)
                    .addComponent(jComboBoxMetodo, 0, 0, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProducto)
                    .addComponent(jComboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMetodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPeriodos)
                    .addComponent(comboBoxPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodoDeInicioLabel)
                    .addComponent(jComboBoxperiodoDeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlfa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBeta)
                    .addComponent(jComboBoxBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGama)
                    .addComponent(jComboBoxGama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelError)
                    .addComponent(jComboBoxError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
    dispose();
}//GEN-LAST:event_botonSalirActionPerformed

private void botonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarActionPerformed
    controlador.predecir();
}//GEN-LAST:event_botonGenerarActionPerformed

private void jComboBoxMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMetodoActionPerformed
    controlador.activarCosas();
}//GEN-LAST:event_jComboBoxMetodoActionPerformed

private void jComboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductoActionPerformed
    controlador.cargarCantidadDePeriodos();
}//GEN-LAST:event_jComboBoxProductoActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox comboBoxPeriodos;
    private javax.swing.JComboBox jComboBoxAlfa;
    private javax.swing.JComboBox jComboBoxBeta;
    private javax.swing.JComboBox jComboBoxError;
    private javax.swing.JComboBox jComboBoxGama;
    private javax.swing.JComboBox jComboBoxMetodo;
    private javax.swing.JComboBox jComboBoxProducto;
    private javax.swing.JComboBox jComboBoxperiodoDeInicio;
    private javax.swing.JLabel jLabelAlfa;
    private javax.swing.JLabel jLabelBeta;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelGama;
    private javax.swing.JLabel jLabelMetodo;
    private javax.swing.JLabel jLabelPeriodos;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel periodoDeInicioLabel;
    // End of variables declaration//GEN-END:variables

    public JButton getBotonGenerar() {
        return botonGenerar;
    }

    public void setBotonGenerar(JButton botonGenerar) {
        this.botonGenerar = botonGenerar;
    }

    public JButton getBotonSalir() {
        return botonSalir;
    }

    public void setBotonSalir(JButton botonSalir) {
        this.botonSalir = botonSalir;
    }

    public JComboBox getComboBoxPeriodos() {
        return comboBoxPeriodos;
    }

    public void setComboBoxPeriodos(JComboBox comboBoxPeriodos) {
        this.comboBoxPeriodos = comboBoxPeriodos;
    }

    public ControladorPrediccionDemanda getControlador() {
        return controlador;
    }

    public void setControlador(ControladorPrediccionDemanda controlador) {
        this.controlador = controlador;
    }

    public JComboBox getjComboBoxAlfa() {
        return jComboBoxAlfa;
    }

    public void setjComboBoxAlfa(JComboBox jComboBoxAlfa) {
        this.jComboBoxAlfa = jComboBoxAlfa;
    }

    public JComboBox getjComboBoxBeta() {
        return jComboBoxBeta;
    }

    public void setjComboBoxBeta(JComboBox jComboBoxBeta) {
        this.jComboBoxBeta = jComboBoxBeta;
    }


    public JComboBox getjComboBoxError() {
        return jComboBoxError;
    }

    public void setjComboBoxError(JComboBox jComboBoxError) {
        this.jComboBoxError = jComboBoxError;
    }

    public JComboBox getjComboBoxGama() {
        return jComboBoxGama;
    }

    public void setjComboBoxGama(JComboBox jComboBoxGama) {
        this.jComboBoxGama = jComboBoxGama;
    }

    public JComboBox getjComboBoxMetodo() {
        return jComboBoxMetodo;
    }

    public void setjComboBoxMetodo(JComboBox jComboBoxMetodo) {
        this.jComboBoxMetodo = jComboBoxMetodo;
    }

    public JComboBox getjComboBoxProducto() {
        return jComboBoxProducto;
    }

    public void setjComboBoxProducto(JComboBox jComboBoxProducto) {
        this.jComboBoxProducto = jComboBoxProducto;
    }

    public JLabel getjLabelAlfa() {
        return jLabelAlfa;
    }

    public void setjLabelAlfa(JLabel jLabelAlfa) {
        this.jLabelAlfa = jLabelAlfa;
    }

    public JLabel getjLabelBeta() {
        return jLabelBeta;
    }

    public void setjLabelBeta(JLabel jLabelBeta) {
        this.jLabelBeta = jLabelBeta;
    }



    public JLabel getjLabelError() {
        return jLabelError;
    }

    public void setjLabelError(JLabel jLabelError) {
        this.jLabelError = jLabelError;
    }

    public JLabel getjLabelGama() {
        return jLabelGama;
    }

    public void setjLabelGama(JLabel jLabelGama) {
        this.jLabelGama = jLabelGama;
    }

    public JLabel getjLabelMetodo() {
        return jLabelMetodo;
    }

    public void setjLabelMetodo(JLabel jLabelMetodo) {
        this.jLabelMetodo = jLabelMetodo;
    }

    public JLabel getjLabelPeriodos() {
        return jLabelPeriodos;
    }

    public void setjLabelPeriodos(JLabel jLabelPeriodos) {
        this.jLabelPeriodos = jLabelPeriodos;
    }

    public JLabel getjLabelProducto() {
        return jLabelProducto;
    }

    public void setjLabelProducto(JLabel jLabelProducto) {
        this.jLabelProducto = jLabelProducto;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JComboBox getjComboBoxperiodoDeInicio() {
        return jComboBoxperiodoDeInicio;
    }

    public void setjComboBoxperiodoDeInicio(JComboBox jComboBoxperiodoDeInicio) {
        this.jComboBoxperiodoDeInicio = jComboBoxperiodoDeInicio;
    }

    public JLabel getPeriodoDeInicioLabel() {
        return periodoDeInicioLabel;
    }

    public void setPeriodoDeInicioLabel(JLabel periodoDeInicioLabel) {
        this.periodoDeInicioLabel = periodoDeInicioLabel;
    }

   
}
